name: (test2) A Docker-based GitHub Action driver
# プライベートアクション版

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: test2-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test2:
    name: A Docker-based GitHub Action driver
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./  # なんか変だけどまちがってない
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was \"${{ steps.hello.outputs.time }}\""
