name: (test3) A Docker-based GitHub Action driver

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: test3-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test3:
    name: A Docker-based GitHub Action driver
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: heiwa4126/docker-action-hello/prebuild@ca00c2abf58bb8ea4d39d934ef87416847bd6811 # v0.0.1
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was \"${{ steps.hello.outputs.time }}\""
